title: Andrei Popescu
description: Technical Writer
show_downloads: false
google_analytics: UA-162628238-1
theme: jekyll-theme-cayman

url: "https://andreipope.github.io" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap

